### ISSUE TITLE
No support for conditions

### ISSUE THREAD

**Issue by marlonparmentier** [schubergphilis/terraform-aws-mcaf-ecr#18]
Policy conditions are currently ignored. I would like to use this module to create an ECR repo that allows all principals originating from a specific OU with below condition (as an example):

      condition = {
        test     = "StringEquals"
        values   = ["OU-PATH"]
        variable = "aws:PrincipalOrgPaths"
        
        The Condition key is currently not copied to the IAM policy generated

**Comment by shoekstra** [comment]
Fixed in #19
